spring:
  data:
    redis:
      host: redis-19553.c54.ap-northeast-1-2.ec2.cloud.redislabs.com
      port: 19553
      username: default
      password: SNka8EkMbBLri9xXLHTfxotVNVLyILZz

  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always