# 특별한 인자 없이 프로젝트 실행 시
# application-dev.yaml을 사용해 프로젝트 실행
spring:
  profiles:
    default: dev

    # 처음에 나오는 Spring Logo 제거
  main:
    banner-mode: off

#logging:
#  level:
##    모든 Logger가 기본으로 적용할 출력 level
#    root: trace
#    com.example.article: debug
#logging:
#  config: file.logback-spring.xml